name: Mork-Test on RISC-V

on:
  push:
    branches: { main }
  pull_request: { main }

jobs:
  build_qemu:
    runs-on: ubuntu-latest
    outputs:
      qemu_ready: ${{ steps.set_output.outputs.ready }}
    steps:
      - name: Checkout (QEMU)
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            libglib2.0-dev \
            libfdt-dev \
            libpixman-1-dev \
            zlib1g-dev \
            ninja-build \
            cmake

      - name: Build QEMU
        run: |
          git clone --depth 1 https://git.qemu.org/qemu.git
          cd qemu
          ./configure --target-list=riscv64-softmmu
          make -j$(nproc)
          echo "QEMU_PATH=$(pwd)/build" >> $GITHUB_ENV

      - name: Set output flag
        id: set_output
        run: echo "::set-output name=ready::true"

  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (Mork Test)
        uses: actions/checkout@v3

      - name: Install rust-toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

      - name: Build Test
        run: |
          mkdir build && cd build
          cmake ..
          make LOG=INFO

  test:
    needs: {build_qemu, build_test}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup QEMU
        run: |
          cd qemu/build
          sudo make install

      - name : Run tests
        run: |
          cd build
          qemu-system-riscv64 -bios fw_jump.bin -kernel os.bin -m 1024M -monitor stdio
      
